# Generated by Django 3.2 on 2021-04-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0002_auto_20210414_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission_reported',
            options={'verbose_name_plural': 'Missions Reported'},
        ),
        migrations.AlterModelOptions(
            name='park',
            options={'verbose_name_plural': 'Park Data'},
        ),
        migrations.AlterModelOptions(
            name='profile_metadata',
            options={'verbose_name_plural': 'Profile Metadata'},
        ),
    ]
