# Generated by Django 3.2 on 2021-04-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0024_alter_deployment_platform_number'),
        ('env_data', '0002_auto_20210429_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continuous_profile',
            options={'verbose_name_plural': 'Continuous Profile'},
        ),
        migrations.AlterModelOptions(
            name='discrete_profile',
            options={'verbose_name_plural': 'Discrete Profile'},
        ),
        migrations.AlterField(
            model_name='mission_reported',
            name='DEPLOYMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_reported', to='deployments.deployment'),
        ),
        migrations.AlterField(
            model_name='park',
            name='DEPLOYMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='park', to='deployments.deployment'),
        ),
        migrations.AlterField(
            model_name='park',
            name='OPH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='OTV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='PRES',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='PSAL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='TEMP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_metadata',
            name='DEPLOYMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_metadata', to='deployments.deployment'),
        ),
    ]
