# Generated by Django 3.2 on 2021-04-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0004_auto_20210429_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle_metadata',
            old_name='gps_lat',
            new_name='GpsLat',
        ),
        migrations.RenameField(
            model_name='cycle_metadata',
            old_name='gps_lon',
            new_name='GpsLong',
        ),
    ]
