# Generated by Django 3.2 on 2021-04-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0005_auto_20210429_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='GpsFixDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
