# Generated by Django 3.2 on 2021-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0006_cycle_metadata_gpsfixdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='GpsNsat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
