# Generated by Django 3.2 on 2021-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0007_cycle_metadata_gpsnsat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='IsusPowerCycleCounter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
