# Generated by Django 3.2 on 2021-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0008_cycle_metadata_isuspowercyclecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='ParkObs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
