# Generated by Django 3.2 on 2021-04-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0010_cycle_metadata_phbaseamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='pHBatteryInVolts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
