# Generated by Django 3.2 on 2021-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0011_cycle_metadata_phbatteryinvolts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='pHBatteryOutVolts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
