# Generated by Django 3.2 on 2021-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0012_cycle_metadata_phbatteryoutvolts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='pHCounterVolts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
