# Generated by Django 3.2 on 2021-04-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0014_cycle_metadata_phcounteramps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='ParkDescentP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='RtcSkew',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
