# Generated by Django 3.2 on 2021-04-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0015_auto_20210429_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle_metadata',
            name='ParkObs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
