# Generated by Django 3.2 on 2021-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0017_auto_20210429_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='OPH',
        ),
        migrations.RemoveField(
            model_name='park',
            name='OTV',
        ),
        migrations.AddField(
            model_name='park',
            name='IB_PH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='IK_PH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='PHASE_DELAY_DOXY',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='RAW_DOWNWELLING_PAR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='RAW_DOWN_IRRADIANCE380',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='RAW_DOWN_IRRADIANCE412',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='RAW_DOWN_IRRADIANCE490',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='TEMP_VOLTAGE_DOXY',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='TILT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='VK_PH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='VRS_PH',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
