# Generated by Django 3.2 on 2021-05-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0018_auto_20210429_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='MISSION',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='env_data.mission_reported', to_field='PROFILE_ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='PROFILE_METADATA',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='env_data.cycle_metadata', to_field='PROFILE_ID'),
            preserve_default=False,
        ),
    ]
