# Generated by Django 3.2 on 2021-05-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0020_auto_20210513_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle_metadata',
            name='Ocr504Amps',
        ),
        migrations.RemoveField(
            model_name='cycle_metadata',
            name='Ocr504Volts',
        ),
        migrations.AlterField(
            model_name='cycle_metadata',
            name='McomsAmps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle_metadata',
            name='McomsVolts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle_metadata',
            name='Sbe63Amps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle_metadata',
            name='Sbe63Volts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
