# Generated by Django 3.2 on 2021-05-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0021_auto_20210513_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='Ocr504Amps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='Ocr504Volts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
