# Generated by Django 3.2 on 2021-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0022_auto_20210513_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='CONNECTIONS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='CONNECTION_ATTEMPTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='GPS_DURATION',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='ISUS_BYTES',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='LOG_BYTES',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='MSG_BYTES',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='TRANS_DURATION',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
