# Generated by Django 3.2 on 2021-05-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0023_auto_20210517_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle_metadata',
            name='UPLOADS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle_metadata',
            name='UPLOAD_ATTEMPTS',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
