# Generated by Django 3.2 on 2021-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0024_auto_20210517_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle_metadata',
            name='ParkDescentP',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
