# Generated by Django 3.2 on 2021-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0025_alter_cycle_metadata_parkdescentp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuous_profile',
            name='MISSION',
        ),
        migrations.RemoveField(
            model_name='continuous_profile',
            name='PROFILE_METADATA',
        ),
        migrations.RemoveField(
            model_name='discrete_profile',
            name='MISSION',
        ),
        migrations.RemoveField(
            model_name='discrete_profile',
            name='PROFILE_METADATA',
        ),
        migrations.RemoveField(
            model_name='park',
            name='MISSION',
        ),
        migrations.RemoveField(
            model_name='park',
            name='PROFILE_METADATA',
        ),
        migrations.AddField(
            model_name='continuous_profile',
            name='PROFILE_ID',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='discrete_profile',
            name='PROFILE_ID',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='park',
            name='PROFILE_ID',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='cycle_metadata',
            name='PROFILE_ID',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mission_reported',
            name='PROFILE_ID',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
