# Generated by Django 3.2.11 on 2022-03-04 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0059_deployment_processing_active'),
        ('env_data', '0026_auto_20210520_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='nitrate_continuous_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_ADD', models.DateTimeField()),
                ('PROFILE_ID', models.CharField(default=0, max_length=20)),
                ('SAMPLE_TIME', models.DateTimeField()),
                ('DARK_CURRENT', models.FloatField(blank=True, null=True, verbose_name='Dark Current')),
                ('PRES', models.FloatField(blank=True, null=True, verbose_name='Pressure dbar')),
                ('NO3', models.FloatField(blank=True, null=True, verbose_name='Nitrate umol/kg')),
                ('BL_B', models.FloatField(blank=True, null=True, verbose_name='Baseline Incercept')),
                ('BL_M', models.FloatField(blank=True, null=True, verbose_name='Baseline Slope')),
                ('RMS_ERROR', models.FloatField(blank=True, null=True, verbose_name='RMS Error')),
                ('WL_240', models.FloatField(blank=True, null=True)),
                ('ABS_240', models.FloatField(blank=True, null=True)),
                ('DEPLOYMENT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deployments.deployment')),
            ],
            options={
                'verbose_name_plural': 'Nitrate Continuous Profile',
            },
        ),
    ]
