# Generated by Django 3.2.11 on 2022-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_data', '0027_nitrate_continuous_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nitrate_continuous_profile',
            name='PSAL',
            field=models.FloatField(blank=True, null=True, verbose_name='Salinity'),
        ),
        migrations.AddField(
            model_name='nitrate_continuous_profile',
            name='TEMP',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature C'),
        ),
    ]
