# Generated by Django 3.2 on 2021-04-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADD_DATE', models.DateTimeField()),
                ('DEPLOYMENT', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='missions', to='deployments.deployment')),
            ],
        ),
    ]
