# Generated by Django 3.2 on 2021-04-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADD_DATE', models.DateTimeField()),
                ('SENSOR', models.CharField(max_length=25)),
                ('SENSOR_MAKER', models.CharField(blank=True, max_length=25, null=True)),
                ('SENSOR_MODEL', models.CharField(blank=True, max_length=25, null=True)),
                ('SENSOR_SERIAL_NO', models.CharField(blank=True, max_length=25, null=True)),
                ('SENSOR_CALIB_DATE', models.DateField(blank=True, null=True)),
                ('PREDEPLOYMENT_CALIB_EQUATION', models.JSONField(blank=True, max_length=100, null=True)),
                ('PREDEPLOYMENT_CALIB_COEFFICIENT', models.JSONField(blank=True, max_length=100, null=True)),
                ('COMMENTS', models.TextField(blank=True, null=True)),
                ('DEPLOYMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='deployments.deployment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(check=models.Q(('SENSOR__in', ['bs']), ('SENSOR_MAKER__in', ['bs']), ('SENSOR_MODEL__in', ['bs'])), name='sensors_sensor_SENSOR_CHECKS'),
        ),
    ]
