# Generated by Django 3.2 on 2021-04-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensor',
            name='sensors_sensor_SENSOR_CHECKS',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR',
            field=models.CharField(blank=True, choices=[('CTD_PRES', 'pressure'), ('CTD_TEMP', 'temperature'), ('CTD_CNDC', 'conductivity'), ('IDO_DOXY', 'oxygen'), ('OPTODE_DOXY', 'oxygen'), ('TRANSISTOR_PH', 'pH')], max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(check=models.Q(('SENSOR__in', ['CTD_PRES', 'CTD_TEMP', 'CTD_CNDC', 'IDO_DOXY', 'OPTODE_DOXY', 'TRANSISTOR_PH']), ('SENSOR_MAKER__in', ['AANDERAA', 'AMETEK', 'SATLANTIC', 'SEB', 'WETLABS']), ('SENSOR_MODEL__in', ['SBE41CP'])), name='sensors_sensor_SENSOR_CHECKS'),
        ),
    ]
