# Generated by Django 3.2 on 2021-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20210414_1425'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensor',
            name='sensors_sensor_SENSOR_CHECKS',
        ),
        migrations.AddField(
            model_name='sensor',
            name='COMMENTS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='SENSOR_CALIB_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR',
            field=models.CharField(blank=True, choices=[('CTD_PRES', 'pressure'), ('CTD_TEMP', 'temperature'), ('CTD_CNDC', 'conductivity'), ('IDO_DOXY', 'oxygen ido'), ('OPTODE_DOXY', 'oxygen optode'), ('TRANSISTOR_PH', 'pH'), ('SPECTROPHOTOMETER_NITRATE', 'nitrate'), ('FLUOROMETER_CHLA', 'flurometer chla')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR_MAKER',
            field=models.CharField(blank=True, choices=[('AANDERAA', 'AANDERAA'), ('AMETEK', 'AMETEK'), ('SATLANTIC', 'SATLANTIC'), ('SBE', 'SBE'), ('WETLABS', 'WETLABS')], max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(check=models.Q(('SENSOR__in', ['CTD_PRES', 'CTD_TEMP', 'CTD_CNDC', 'IDO_DOXY', 'OPTODE_DOXY', 'TRANSISTOR_PH', 'SPECTROPHOTOMETER_NITRATE', 'FLUOROMETER_CHLA']), ('SENSOR_MAKER__in', ['AANDERAA', 'AMETEK', 'SATLANTIC', 'SBE', 'WETLABS']), ('SENSOR_MODEL__in', ['SBE41CP'])), name='sensors_sensor_SENSOR_CHECKS'),
        ),
    ]
