# Generated by Django 3.2 on 2021-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_remove_sensor_sensors_sensor_sensor_checks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(check=models.Q(('SENSOR__in', ['FLUOROMETER_CHLA']), ('SENSOR_MAKER__in', ['JAC']), ('SENSOR_MODEL__in', ['SBE41CP_V1.8'])), name='sensors_sensor_SENSOR_CHECKS'),
        ),
    ]
