# Generated by Django 3.2 on 2021-04-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20210414_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR_CALIB_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
