# Generated by Django 3.2 on 2021-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20210419_1520'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensor',
            name='sensors_sensor_SENSOR_CHECKS',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR',
            field=models.CharField(choices=[('FLUOROMETER_CHLA', 'FLUOROMETER_CHLA'), ('TRANSISTOR_PH', 'TRANSISTOR_PH'), ('CTD_CNDC', 'CTD_CNDC'), ('CTD_PRES', 'CTD_PRES'), ('CTD_TEMP', 'CTD_TEMP'), ('OPTODE_DOXY', 'OPTODE_DOXY'), ('SPECTROPHOTOMETER_NITRATE', 'SPECTROPHOTOMETER_NITRATE'), ('FLUOROMETER_CDOM', 'FLUOROMETER_CDOM'), ('RADIOMETER_PAR', 'RADIOMETER_PAR'), ('BACKSCATTERINGMETER_BBP700', 'BACKSCATTERINGMETER_BBP700'), ('PUMP_VOLTAGE', 'PUMP_VOLTAGE'), ('CPU_VOLTAGE', 'CPU_VOLTAGE')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(check=models.Q(('SENSOR__in', ['FLUOROMETER_CHLA', 'TRANSISTOR_PH', 'CTD_CNDC', 'CTD_PRES', 'CTD_TEMP', 'OPTODE_DOXY', 'SPECTROPHOTOMETER_NITRATE', 'FLUOROMETER_CDOM', 'RADIOMETER_PAR', 'BACKSCATTERINGMETER_BBP700', 'PUMP_VOLTAGE', 'CPU_VOLTAGE']), ('SENSOR_MAKER__in', ['JAC', 'WETLABS', 'SBE', 'MBARI', 'DRUCK', 'SATLANTIC']), ('SENSOR_MODEL__in', ['DRUCK_2900PSIA', 'SBE41CP_V3.0c', 'DURAFET', 'MCOMS', 'SBE63_V3.2.2', 'SUNA_V2'])), name='sensors_sensor_SENSOR_CHECKS'),
        ),
    ]
