# Generated by Django 3.2 on 2021-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_sensor_sensor_calib_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR',
            field=models.CharField(choices=[('CTD_PRES', 'pressure'), ('CTD_TEMP', 'temperature'), ('CTD_CNDC', 'conductivity'), ('IDO_DOXY', 'oxygen ido'), ('OPTODE_DOXY', 'oxygen optode'), ('TRANSISTOR_PH', 'pH'), ('SPECTROPHOTOMETER_NITRATE', 'nitrate'), ('FLUOROMETER_CHLA', 'flurometer chla')], default='pressure', max_length=25),
            preserve_default=False,
        ),
    ]
