# Generated by Django 3.2 on 2021-04-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_alter_sensor_deployment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensor',
            name='sensors_sensor_SENSOR_CHECKS',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR',
            field=models.CharField(choices=[('CTD_PRES', 'pressure'), ('CTD_TEMP', 'temperature'), ('CTD_CNDC', 'conductivity'), ('OPTODE_DOXY', 'oxygen optode'), ('TRANSISTOR_PH', 'pH'), ('SPECTROPHOTOMETER_NITRATE', 'nitrate'), ('FLUOROMETER_CHLA', 'flurometer chla')], max_length=25),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(check=models.Q(('SENSOR__in', ['CTD_PRES', 'CTD_TEMP', 'CTD_CNDC', 'OPTODE_DOXY', 'TRANSISTOR_PH', 'SPECTROPHOTOMETER_NITRATE', 'FLUOROMETER_CHLA']), ('SENSOR_MAKER__in', ['AANDERAA', 'AMETEK', 'SATLANTIC', 'SBE', 'WETLABS']), ('SENSOR_MODEL__in', ['SBE41CP'])), name='sensors_sensor_SENSOR_CHECKS'),
        ),
    ]
