# Generated by Django 3.2 on 2021-04-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20210419_1550'),
        ('sensors', '0014_auto_20210423_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='SENSOR_MAKER_TEST',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='choices.sensor_makers'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR_MAKER',
            field=models.CharField(blank=True, choices=[('JAC', 'JFE Advantech Co., Ltd'), ('SBE', 'Sea-Bird Scientific'), ('MBARI', 'Monterey Bay Aquarium Research Institute'), ('DRUCK', 'Druck Inc.'), ('SATLANTIC', 'Satlantic Inc.'), ('WETLABS', 'Wetlabs Inc.'), ('PAINE', 'Paine Electronics')], max_length=25, null=True),
        ),
    ]
