# Generated by Django 3.2 on 2021-04-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20210419_1550'),
        ('sensors', '0015_auto_20210423_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_MAKER_TEST',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_MAKER',
        ),
    ]
