# Generated by Django 3.2 on 2021-04-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20210419_1550'),
        ('sensors', '0016_auto_20210423_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='SENSOR_MAKER',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.sensor_makers'),
        ),
    ]
