# Generated by Django 3.2 on 2021-04-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20210419_1550'),
        ('sensors', '0019_alter_sensor_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='SENSOR',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.sensor_types'),
        ),
    ]
