# Generated by Django 3.2 on 2021-04-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20210419_1550'),
        ('sensors', '0021_remove_sensor_sensor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='SENSOR_MODEL',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.sensor_models'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='SENSOR',
            field=models.ForeignKey(default=1, limit_choices_to={'ACTIVE': True}, max_length=50, on_delete=django.db.models.deletion.PROTECT, to='choices.sensor_types'),
            preserve_default=False,
        ),
    ]
