# Generated by Django 3.2 on 2021-04-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0008_auto_20210423_1043'),
        ('sensors', '0024_sensor_sensor'),
    ]

    operations = [
          migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_MAKER',
        ),
    ]
