# Generated by Django 3.2 on 2021-04-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0026_sensor_sensor_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_MODEL',
        ),
    ]
