# Generated by Django 3.2 on 2021-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADD_DATE', models.DateTimeField()),
                ('INTERNAL_ID_NO', models.CharField(blank=True, max_length=25, null=True)),
                ('PLATFORM_NUMBER', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('FLOAT_SERIAL_NO', models.IntegerField(blank=True, null=True)),
                ('PLATFORM_MAKER', models.CharField(blank=True, max_length=25, null=True)),
                ('PLATFORM_TYPE', models.CharField(blank=True, max_length=25, null=True)),
                ('INST_TYPE', models.CharField(blank=True, max_length=25, null=True)),
                ('WMO_INST_TYPE', models.CharField(blank=True, max_length=25, null=True)),
                ('WMO_RECORDER_TYPE', models.CharField(blank=True, max_length=25, null=True)),
                ('TRANS_SYSTEM_ID', models.CharField(blank=True, max_length=25, null=True)),
                ('TRANS_SYSTEM', models.CharField(blank=True, choices=[('IRIDIUM', 'IRIDIUM'), ('ARGOS', 'ARGOS'), ('ORBCOMM', 'ORBCOMM')], default='IRIDIUM', max_length=25, null=True)),
                ('IRIDIUM_PROGRAM_NO', models.CharField(blank=True, max_length=25, null=True)),
                ('START_DATE', models.DateTimeField(blank=True, null=True)),
                ('START_DATE_QC', models.CharField(blank=True, choices=[('estimated', 'estimated')], default='estimated', max_length=25, null=True)),
                ('LAUNCH_DATE', models.DateTimeField(blank=True, null=True)),
                ('LAUNCH_DATE_QC', models.CharField(blank=True, choices=[('estimated', 'estimated')], default='estimated', max_length=25, null=True)),
                ('LAUNCH_LATITUDE', models.FloatField(blank=True, null=True)),
                ('LAUNCH_LONGITUDE', models.FloatField(blank=True, null=True)),
                ('LAUNCH_POSITION_QC', models.CharField(blank=True, choices=[('estimated', 'estimated')], default='estimated', max_length=25, null=True)),
                ('PROJECT_NAME', models.CharField(blank=True, max_length=25, null=True)),
                ('PI_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PI_ADDRESS', models.CharField(blank=True, max_length=100, null=True)),
                ('ORIGIN_COUNTRY', models.CharField(blank=True, max_length=25, null=True)),
                ('DEPLOYER', models.CharField(blank=True, max_length=25, null=True)),
                ('DEPLOYER_ADDRESS', models.CharField(blank=True, max_length=100, null=True)),
                ('DEPLOYMENT_TYPE', models.CharField(blank=True, max_length=25, null=True)),
                ('DEPLOYMENT_PLATFORM', models.CharField(blank=True, max_length=25, null=True)),
                ('DEPLOYMENT_CRUISE_ID', models.CharField(blank=True, max_length=25, null=True)),
                ('DEPLOYMENT_REFERENCE_STATION_ID', models.CharField(blank=True, max_length=25, null=True)),
                ('DEPLOYMENT_PLATFORM_ID', models.CharField(blank=True, max_length=25, null=True)),
                ('PTT', models.CharField(blank=True, max_length=25, null=True)),
                ('CPU_SERIAL_NO', models.CharField(blank=True, max_length=25, null=True)),
                ('ROM_VERSION', models.CharField(blank=True, max_length=25, null=True)),
                ('BATTERY_TYPE', models.CharField(blank=True, max_length=25, null=True)),
                ('BATTERY_MANUFACTURER', models.CharField(blank=True, max_length=25, null=True)),
                ('BATTERY_SERIAL_NO', models.CharField(blank=True, max_length=25, null=True)),
                ('BATTERY_VOLTAGE', models.FloatField(blank=True, max_length=25, null=True)),
                ('BATTERY_PACKS', models.CharField(blank=True, max_length=25, null=True)),
                ('BATTERY_DETAILS', models.CharField(blank=True, max_length=25, null=True)),
                ('PUMP_BATTERY_SERIAL_NO', models.IntegerField(blank=True, null=True)),
                ('CUSTOMIZATION', models.CharField(blank=True, max_length=200, null=True)),
                ('COMMENTS', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.CheckConstraint(check=models.Q(('TRANS_SYSTEM__in', ['IRIDIUM', 'ARGOS', 'ORBCOMM']), ('START_DATE_QC__in', ['estimated']), ('LAUNCH_DATE_QC__in', ['estimated']), ('LAUNCH_POSITION_QC__in', ['estimated']), ('LAUNCH_LATITUDE__lte', 90), ('LAUNCH_LATITUDE__gte', -90), ('LAUNCH_LONGITUDE__lte', 180), ('LAUNCH_LONGITUDE__gte', -180)), name='deployments_deployment_CHECKS'),
        ),
    ]
