# Generated by Django 3.2 on 2021-04-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_remove_deployment_cpu_serial_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deployment',
            name='deployments_deployment_CHECKS',
        ),
        migrations.AddField(
            model_name='deployment',
            name='ADD_DATE_TEST',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='DEPLOYMENT_TYPE',
            field=models.CharField(blank=True, choices=[('RV', 'RV'), ('VOS', 'VOS')], max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.CheckConstraint(check=models.Q(('TRANS_SYSTEM__in', ['IRIDIUM', 'ARGOS', 'ORBCOMM']), ('START_DATE_QC__in', ['estimated']), ('LAUNCH_DATE_QC__in', ['estimated']), ('LAUNCH_POSITION_QC__in', ['estimated']), ('DEPLOYMENT_TYPE__in', ['RV', 'VOS']), ('LAUNCH_LATITUDE__lte', 90), ('LAUNCH_LATITUDE__gte', -90), ('LAUNCH_LONGITUDE__lte', 180), ('LAUNCH_LONGITUDE__gte', -180)), name='deployments_deployment_CHECKS'),
        ),
    ]
