# Generated by Django 3.2 on 2021-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_auto_20210419_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='PLATFORM_MAKER',
            field=models.CharField(blank=True, choices=[('841', '841')], max_length=25, null=True),
        ),
    ]
