# Generated by Django 3.2 on 2021-04-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_auto_20210416_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='ADD_DATE',
            new_name='ADD_DATEd',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='ADD_DATE_TEST',
        ),
    ]
