# Generated by Django 3.2 on 2021-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_auto_20210419_1357'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deployment',
            name='deployments_deployment_CHECKS',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='DEPLOYMENT_TYPE',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='PLATFORM_MAKER',
            field=models.CharField(blank=True, choices=[('MRV', 'MRV'), ('SBE', 'SBE')], max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.CheckConstraint(check=models.Q(('TRANS_SYSTEM__in', ['IRIDIUM', 'ARGOS', 'ORBCOMM']), ('START_DATE_QC__in', ['estimated', 'as recorded']), ('LAUNCH_DATE_QC__in', ['estimated', 'as recorded']), ('LAUNCH_POSITION_QC__in', ['estimated', 'as recorded']), ('DEPLOYMENT_TYPE__in', ['RV', 'VOS', 'RRS']), ('WMO_INST_TYPE__in', ['841']), ('PLATFORM_MAKER__in', ['MRV', 'SBE']), ('LAUNCH_LATITUDE__lte', 90), ('LAUNCH_LATITUDE__gte', -90), ('LAUNCH_LONGITUDE__lte', 180), ('LAUNCH_LONGITUDE__gte', -180)), name='deployments_deployment_CHECKS'),
        ),
    ]
