# Generated by Django 3.2 on 2021-04-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_auto_20210416_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='ADD_DATEd',
            new_name='ADD_DATE',
        ),
    ]
