# Generated by Django 3.2 on 2021-04-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_auto_20210419_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='TRANS_SYSTEM_ID',
        ),
        migrations.AddField(
            model_name='deployment',
            name='BATTERY_MODEL',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
