# Generated by Django 3.2 on 2021-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0012_auto_20210420_1127'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deployment',
            name='deployments_deployment_CHECKS',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='PLATFORM_MAKER',
            field=models.CharField(blank=True, choices=[('MRV', 'MRV Systems'), ('SBE', 'Sea-Bird Scientific')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='PLATFORM_TYPE',
            field=models.CharField(blank=True, choices=[('S2A', 'S2-A float'), ('NAVIS_EBR', 'NAVIS_EBR float')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='TRANS_SYSTEM',
            field=models.CharField(blank=True, choices=[('ARGOS', 'Argos transmission system'), ('IRIDIUM', 'Iridium transmission system')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='WMO_INST_TYPE',
            field=models.CharField(blank=True, choices=[('880', 'S2A float with RBR conductivity sensor'), ('854', 'S2A float with SBE conductivity sensor'), ('863', 'Navis-A float with SBE conductivity sensor')], max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.CheckConstraint(check=models.Q(('START_DATE_QC__in', ['estimated', 'as recorded']), ('LAUNCH_DATE_QC__in', ['estimated', 'as recorded']), ('LAUNCH_POSITION_QC__in', ['estimated', 'as recorded']), ('DEPLOYMENT_TYPE__in', ['RV', 'VOS', 'RRS']), ('WMO_INST_TYPE__in', ['880', '854', '863']), ('PLATFORM_MAKER__in', ['MRV', 'SBE']), ('PLATFORM_TYPE__in', ['S2A', 'NAVIS_EBR']), ('TRANS_SYSTEM__in', ['ARGOS', 'IRIDIUM']), ('LAUNCH_LATITUDE__lte', 90), ('LAUNCH_LATITUDE__gte', -90), ('LAUNCH_LONGITUDE__lte', 180), ('LAUNCH_LONGITUDE__gte', -180)), name='deployments_deployment_CHECKS'),
        ),
    ]
