# Generated by Django 3.2 on 2021-04-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0017_auto_20210423_0830'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deployment',
            name='deployments_deployment_CHECKS',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='PLATFORM_MAKER',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='PLATFORM_TYPE',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='TRANS_SYSTEM',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='WMO_INST_TYPE',
        ),
    ]
