# Generated by Django 3.2 on 2021-04-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20210419_1550'),
        ('deployments', '0018_auto_20210423_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='PLATFORM_MAKER',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.platform_makers'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='PLATFORM_TYPE',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.platform_types'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='TRANS_SYSTEM',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.transmission_systems'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='WMO_INST_TYPE',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.instrument_types'),
        ),
    ]
