# Generated by Django 3.2 on 2021-04-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0008_auto_20210423_1043'),
        ('deployments', '0020_auto_20210423_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='PLATFORM_MAKER',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.platform_makers', to_field='VALUE'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='PLATFORM_TYPE',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.platform_types', to_field='VALUE'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='TRANS_SYSTEM',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.transmission_systems', to_field='VALUE'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='WMO_INST_TYPE',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.instrument_types', to_field='VALUE'),
        ),
    ]
