# Generated by Django 3.2 on 2021-04-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0009_funders_institutions'),
        ('deployments', '0021_auto_20210423_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='PROJECT_NAME',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='PTT',
        ),
        migrations.AddField(
            model_name='deployment',
            name='FUNDER',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.funders', to_field='VALUE'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='INSTITUTION',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.institutions', to_field='VALUE'),
        ),
    ]
