# Generated by Django 3.2 on 2021-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0022_auto_20210427_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='FLOAT_CONTROLLER_SERIAL_NO',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='GPS_SERIAL_NO',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='LBT_SERIAL_NO',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
