# Generated by Django 3.2 on 2021-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0023_auto_20210427_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='PLATFORM_NUMBER',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='PLATFORM NUMBER (WMO)'),
        ),
    ]
