# Generated by Django 3.2 on 2021-04-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0024_alter_deployment_platform_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='MODEM_TYPE',
            field=models.CharField(blank=True, choices=[('Civilian', 'Civilian'), ('DOD', 'Department of Defence')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='PURCHACE_ORDER',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='WHOI_TAG',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
