# Generated by Django 3.2 on 2021-05-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0025_auto_20210429_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='LBT_SERIAL_NO',
            new_name='MODEM_SERIAL_NO',
        ),
    ]
