# Generated by Django 3.2 on 2021-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0027_deployment_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='DEPLOYMENT_MOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='DEPLOYMENT_PORT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
