# Generated by Django 3.2 on 2021-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0029_alter_deployment_deployment_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='INST_TYPE',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='INST TYPE (AOML)'),
        ),
    ]
