# Generated by Django 3.2 on 2021-05-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0032_remove_deployment_deployment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='DEPLOYER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
