# Generated by Django 3.2 on 2021-05-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0034_deployment_platform_type_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='INST_TYPE',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='IRIDIUM_PROGRAM_NO',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='PLATFORM_TYPE',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='WMO_INST_TYPE',
        ),
    ]
