# Generated by Django 3.2 on 2021-05-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0035_auto_20210526_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='PLATFORM_TYPE_INTERNAL',
            new_name='PLATFORM_TYPE',
        ),
    ]
