# Generated by Django 3.2 on 2021-05-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0036_rename_platform_type_internal_deployment_platform_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='DEPLOYMENT_PLATFORM_ID',
        ),
    ]
