# Generated by Django 3.2 on 2021-06-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0038_auto_20210602_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='BATTERY_DETAILS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='BATTERY_PACKS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
