# Generated by Django 3.2 on 2021-06-10 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0021_platform_types_aoml_platform_types_wmo'),
        ('deployments', '0040_alter_deployment_float_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='PLATFORM_TYPE',
        ),
        migrations.AddField(
            model_name='deployment',
            name='PLATFORM_TYPE_AOML',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.platform_types_aoml', to_field='VALUE'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='PLATFORM_TYPE_WMO',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.platform_types_wmo', to_field='VALUE'),
        ),
    ]
