# Generated by Django 3.2 on 2021-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0043_auto_20210610_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='HISTORICAL',
            field=models.BooleanField(default=False),
        ),
    ]
