# Generated by Django 3.2 on 2021-06-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0044_deployment_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='DEPLOYMENT_CRUISE_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
