# Generated by Django 3.2 on 2021-06-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0046_auto_20210616_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='DEPLOYMENT_REFERENCE_STATION_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
