# Generated by Django 3.2 on 2021-06-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0047_alter_deployment_deployment_reference_station_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='PURCHACE_ORDER',
            new_name='PURCHASE_ORDER',
        ),
    ]
