# Generated by Django 3.2.6 on 2021-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0049_auto_20210818_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='DRY_WEIGHT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
