# Generated by Django 3.2 on 2021-12-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0054_remove_deployment_deployment_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='DEPLOYMENT_PLATFORM_C17',
            new_name='DEPLOYMENT_PLATFORM',
        ),
    ]
