# Generated by Django 3.2 on 2021-12-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0032_deployment_platforms'),
        ('deployments', '0055_rename_deployment_platform_c17_deployment_deployment_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='DEPLOYMENT_PLATFORM_OLD',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OLD', to='choices.deployment_platforms_c17'),
        ),
    ]
