# Generated by Django 3.2 on 2021-12-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0032_deployment_platforms'),
        ('deployments', '0056_deployment_deployment_platform_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='DEPLOYMENT_PLATFORM',
            field=models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.deployment_platforms'),
        ),
    ]
