# Generated by Django 3.2.6 on 2022-01-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0058_remove_deployment_deployment_platform_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='PROCESSING_ACTIVE',
            field=models.BooleanField(default=False),
        ),
    ]
