# Generated by Django 3.2.11 on 2022-01-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0028_sensor_sensor_model'),
        ('choices', '0034_qc_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_qc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADD_DATE', models.DateTimeField()),
                ('START_CYCLE', models.IntegerField(blank=True, null=True, verbose_name='Start Cycle - Inclusive')),
                ('END_CYCLE', models.IntegerField(blank=True, null=True, verbose_name='End Cycle - Inclusive')),
                ('PROBLEM', models.TextField(blank=True, null=True)),
                ('QC_LEVEL', models.ForeignKey(blank=True, limit_choices_to={'ACTIVE': True}, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.qc_levels', to_field='VALUE')),
                ('SENSOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_qc', to='sensors.sensor')),
            ],
            options={
                'verbose_name_plural': 'Sensor QC',
            },
        ),
    ]
