# Generated by Django 3.2.11 on 2022-01-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0028_sensor_sensor_model'),
        ('sensor_qc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_qc',
            name='SENSOR',
            field=models.ForeignKey(limit_choices_to={'DEPLOYMENT__HISTORICAL': False}, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_qc', to='sensors.sensor'),
        ),
    ]
