# Generated by Django 3.2.11 on 2022-03-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0035_remove_qc_levels_active'),
        ('sensor_qc', '0002_alter_sensor_qc_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_qc',
            name='QC_LEVEL',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.qc_levels', to_field='VALUE'),
        ),
    ]
