# Generated by Django 3.2 on 2021-04-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADD_DATE', models.DateTimeField()),
                ('AscentTimeOut', models.IntegerField(blank=True, null=True)),
                ('BuoyancyNudge', models.IntegerField(blank=True, null=True)),
                ('BuoyancyNudgeInitial', models.IntegerField(blank=True, null=True)),
                ('ConnectTimeOut', models.IntegerField(blank=True, null=True)),
                ('CpActivationP', models.IntegerField(blank=True, null=True)),
                ('DeepProfileDescentTime', models.IntegerField(blank=True, null=True)),
                ('DeepProfileBuoyancyPos', models.IntegerField(blank=True, null=True)),
                ('DeepProfilePressure', models.IntegerField(blank=True, null=True)),
                ('DownTime', models.IntegerField(blank=True, null=True)),
                ('FloatId', models.CharField(blank=True, max_length=25, null=True)),
                ('FullExtension', models.IntegerField(blank=True, null=True)),
                ('FullRetraction', models.IntegerField(blank=True, null=True)),
                ('IceDetectionP', models.FloatField(blank=True, null=True)),
                ('IceEvasionP', models.FloatField(blank=True, null=True)),
                ('IceMLTCritical', models.FloatField(blank=True, null=True)),
                ('IceMonths', models.CharField(blank=True, max_length=25, null=True)),
                ('IsusInit', models.IntegerField(blank=True, null=True)),
                ('HpvEmfK', models.FloatField(blank=True, null=True)),
                ('HpvRes', models.IntegerField(blank=True, null=True)),
                ('MaxAirBladder', models.IntegerField(blank=True, null=True)),
                ('MaxLogKb', models.IntegerField(blank=True, null=True)),
                ('MissionPrelude', models.IntegerField(blank=True, null=True)),
                ('OkVacuum', models.IntegerField(blank=True, null=True)),
                ('PActivationBuoyancyPosition', models.IntegerField(blank=True, null=True)),
                ('ParkDescentTime', models.IntegerField(blank=True, null=True)),
                ('ParkBuoyancyPos', models.IntegerField(blank=True, null=True)),
                ('ParkPressure', models.IntegerField(blank=True, null=True)),
                ('PnPCycleLen', models.IntegerField(blank=True, null=True)),
                ('TelemetryRetry', models.IntegerField(blank=True, null=True)),
                ('TimeOfDay', models.IntegerField(blank=True, null=True)),
                ('UpTime', models.IntegerField(blank=True, null=True)),
                ('PhBattMode', models.IntegerField(blank=True, null=True)),
                ('Verbosity', models.IntegerField(blank=True, null=True)),
                ('DebugBits', models.CharField(blank=True, max_length=25, null=True)),
                ('COMMENTS', models.TextField(blank=True, null=True)),
                ('DEPLOYMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='deployments.deployment')),
            ],
        ),
    ]
