# Generated by Django 3.2 on 2021-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_missionsignature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='FloatId',
        ),
        migrations.AlterField(
            model_name='mission',
            name='AscentTimeOut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ascent time-out (Minutes) Mta'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='BuoyancyNudge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ascent buoyancy nudge (Counts) Mbn'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='BuoyancyNudgeInitial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Initial buoyancy nudge (Counts) Mbi'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ConnectTimeOut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Host-connect time-out (Seconds) Mht'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='CpActivationP',
            field=models.IntegerField(blank=True, null=True, verbose_name='Continuous profile activation (Decibars) Mc'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='DebugBits',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='DebugBits D'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='DeepProfileBuoyancyPos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deep-profile buoyancy position (Counts) Mbj'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='DeepProfileDescentTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deep-profile descent time (Minutes) Mtj'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='DeepProfilePressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deep-profile pressure (Decibars) Mj'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='DownTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Down time (Minutes) Mtd'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='FullExtension',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buoyancy full extension (Counts) Mff'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='FullRetraction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buoyancy full retraction (Counts) Mfr'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='HpvEmfK',
            field=models.FloatField(blank=True, null=True, verbose_name='HPV b-EMF coefficient (Volt-Sec/Rad) Mfk'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='HpvRes',
            field=models.IntegerField(blank=True, null=True, verbose_name='HPV winding resistance (Ohms) Mfw'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='IceDetectionP',
            field=models.FloatField(blank=True, null=True, verbose_name='Ice detection: Mixed-layer Pmax (Decibars) Mix'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='IceEvasionP',
            field=models.FloatField(blank=True, null=True, verbose_name='Ice detection: Mixed-layer Pmin (Decibars) Min'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='IceMLTCritical',
            field=models.FloatField(blank=True, null=True, verbose_name='Ice detection: Mixed-layer Tcritical (C) Mit'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='IceMonths',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Ice detection: Winter months [DNOSAJJMAMFJ] Mib'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='MaxAirBladder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum air bladder pressure (Counts) Mfb'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='MissionPrelude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mission prelude (Minutes) Mtp'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='MissionSignature',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Mission signature (hex)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='OkVacuum',
            field=models.IntegerField(blank=True, null=True, verbose_name='OK vacuum threshold (Counts) Mfv'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='PActivationBuoyancyPosition',
            field=models.IntegerField(blank=True, null=True, verbose_name='P-Activation buoyancy position (Counts) Mfs'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ParkBuoyancyPos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Park buoyancy position (Counts) Mbp'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ParkDescentTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Park descent time (Minutes) Mtk'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ParkPressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='Park pressure (Decibars) Mk'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='PnPCycleLen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Park-n-profile cycle length Mn'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='TelemetryRetry',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telemetry retry interval (Minutes) Mhr'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='TimeOfDay',
            field=models.IntegerField(blank=True, null=True, verbose_name='ToD for down-time expiration (Minutes) Mtc'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='UpTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Up time (Minutes) Mtu'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='Verbosity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Logging verbosity [0-5] D'),
        ),
    ]
