# Generated by Django 3.2 on 2021-04-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20210414_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='COMMENTS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
