# Generated by Django 3.2 on 2021-04-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_rename_internal_id_no_deployment_aoml_id'),
        ('missions', '0003_mission_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='DEPLOYMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='deployments.deployment'),
        ),
    ]
