# Generated by Django 3.2 on 2021-06-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_mission_activaterecoverymode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ('-ADD_DATE',)},
        ),
    ]
