# Generated by Django 3.2 on 2021-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DIRECTORY', models.CharField(max_length=200, unique=True)),
                ('STATUS', models.CharField(max_length=200)),
                ('DATE', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'File Processing',
            },
        ),
    ]
