# Generated by Django 3.2 on 2021-04-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_processing',
            name='DETAILS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
