# Generated by Django 3.2 on 2021-04-29 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0011_events'),
        ('deployments', '0024_alter_deployment_platform_number'),
        ('logs', '0002_file_processing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_processing',
            name='STATUS',
            field=models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail')], max_length=200),
        ),
        migrations.CreateModel(
            name='deployment_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOCATION', models.CharField(blank=True, max_length=100, null=True)),
                ('COMMENT', models.TextField(blank=True, null=True)),
                ('DEPLOYMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment')),
                ('EVENT', models.ForeignKey(limit_choices_to={'ACTIVE': True}, max_length=50, on_delete=django.db.models.deletion.PROTECT, to='choices.events', to_field='VALUE')),
            ],
            options={
                'verbose_name_plural': 'Deployment Tracking',
            },
        ),
    ]
