# Generated by Django 3.2 on 2021-04-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20210428_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_processing',
            name='STATUS',
            field=models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail'), ('Skip', 'Skip')], max_length=200),
        ),
    ]
