# Generated by Django 3.2 on 2021-06-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0037_remove_deployment_deployment_platform_id'),
        ('logs', '0006_alter_file_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment_tracking',
            name='DEPLOYMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_tracking', to='deployments.deployment'),
        ),
    ]
