# Generated by Django 3.2 on 2021-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alter_file_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_processing',
            name='CYCLE',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='file_processing',
            name='FLOAT_SERIAL_NO',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
