# Generated by Django 3.2.11 on 2022-03-01 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_alter_deployment_tracking_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_processing',
            old_name='DATE',
            new_name='DATE_PROCESSED',
        ),
        migrations.AddField(
            model_name='file_processing',
            name='DATE_FILE_MODIFIED',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
