# Generated by Django 3.2 on 2021-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instrument_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=50)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('SOURCE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Intrument Types',
            },
        ),
        migrations.CreateModel(
            name='sensor_makers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=50)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('SOURCE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Sensor Makers',
            },
        ),
        migrations.CreateModel(
            name='sensor_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=50)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('SOURCE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Sensor Models',
            },
        ),
        migrations.CreateModel(
            name='sensor_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=50)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('SOURCE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Sensor Types',
            },
        ),
    ]
