# Generated by Django 3.2 on 2021-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='platform_makers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=50)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('SOURCE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Platform Makers',
            },
        ),
    ]
