# Generated by Django 3.2 on 2021-04-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_platform_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform_types',
            options={'verbose_name_plural': 'Platform Types'},
        ),
    ]
