# Generated by Django 3.2 on 2021-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_alter_platform_types_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='transmission_systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=50)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('SOURCE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Transmission Systems',
            },
        ),
    ]
