# Generated by Django 3.2 on 2021-04-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20210419_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_types',
            name='VALUE',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
