# Generated by Django 3.2 on 2021-04-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0007_alter_sensor_types_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument_types',
            name='VALUE',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='platform_makers',
            name='VALUE',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='platform_types',
            name='VALUE',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor_makers',
            name='VALUE',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor_models',
            name='VALUE',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transmission_systems',
            name='VALUE',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
