# Generated by Django 3.2 on 2021-04-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0009_funders_institutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funders',
            name='SOURCE',
        ),
        migrations.RemoveField(
            model_name='institutions',
            name='SOURCE',
        ),
        migrations.AlterField(
            model_name='funders',
            name='DESCRIPTION',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='DESCRIPTION',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
