# Generated by Django 3.2 on 2021-04-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0010_auto_20210427_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=100, unique=True)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('DESCRIPTION', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
