# Generated by Django 3.2 on 2021-05-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0015_deployment_platforms_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment_platforms',
            name='NODC',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='deployment_platforms',
            name='SOURCE',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
