# Generated by Django 3.2 on 2021-05-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0017_platform_types_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_types_internal',
            name='AOML',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
