# Generated by Django 3.2 on 2021-05-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0035_auto_20210526_2004'),
        ('choices', '0018_platform_types_internal_aoml'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instrument_types',
        ),
        migrations.DeleteModel(
            name='instrument_types_AOML',
        ),
        migrations.DeleteModel(
            name='platform_types',
        ),
    ]
