# Generated by Django 3.2 on 2021-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0020_auto_20210526_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='platform_types_aoml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=25, unique=True)),
                ('KEY', models.CharField(max_length=10, unique=True)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('SOURCE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Types - AOML',
            },
        ),
        migrations.CreateModel(
            name='platform_types_wmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=25, unique=True)),
                ('KEY', models.CharField(max_length=10, unique=True)),
                ('DISPLAY', models.CharField(max_length=200)),
                ('ACTIVE', models.BooleanField()),
                ('SOURCE', models.CharField(max_length=50)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Types - WMO',
            },
        ),
    ]
