# Generated by Django 3.2 on 2021-06-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0021_platform_types_aoml_platform_types_wmo'),
        ('deployments', '0041_auto_20210610_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='platform_types',
        ),
    ]
