# Generated by Django 3.2 on 2021-06-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0023_platform_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform_types_aoml',
            name='KEY',
        ),
        migrations.RemoveField(
            model_name='platform_types_wmo',
            name='KEY',
        ),
    ]
