# Generated by Django 3.2 on 2021-12-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0024_auto_20210610_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracking_error_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(max_length=100, unique=True)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tracking - Error Types',
            },
        ),
    ]
