# Generated by Django 3.2 on 2021-12-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0027_auto_20211215_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment_platforms_c17',
            name='ICES',
            field=models.CharField(default=999999, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment_platforms_c17',
            name='VALUE',
            field=models.CharField(max_length=100),
        ),
    ]
