# Generated by Django 3.2 on 2021-12-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0028_auto_20211215_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment_platforms_c17',
            name='ICES',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
