# Generated by Django 3.2 on 2021-12-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0054_remove_deployment_deployment_platform'),
        ('choices', '0029_alter_deployment_platforms_c17_ices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deployment_platforms',
        ),
    ]
