# Generated by Django 3.2 on 2021-12-16 19:08

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0031_alter_deployment_platforms_c17_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='deployment_platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICES', models.CharField(blank=True, max_length=25, null=True)),
                ('VALUE', models.CharField(max_length=100)),
                ('ACTIVE', models.BooleanField()),
                ('TYPE', models.CharField(blank=True, choices=[('R/V', 'R/V'), ('VOS', 'VOS'), ('M/V', 'M/V'), ('AIR', 'AIR')], max_length=25, null=True)),
                ('SOURCE', models.CharField(blank=True, max_length=25, null=True)),
                ('DESCRIPTION', models.JSONField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Deployment Platforms',
                'ordering': ['-ACTIVE', 'VALUE'],
            },
        ),
    ]
