# Generated by Django 3.2 on 2021-12-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0058_remove_deployment_deployment_platform_old'),
        ('choices', '0032_deployment_platforms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deployment_platforms_C17',
        ),
    ]
