# Generated by Django 3.2.11 on 2022-01-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0034_qc_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qc_levels',
            name='ACTIVE',
        ),
    ]
