# Generated by Django 3.2 on 2021-04-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADD_DATE', models.DateTimeField()),
                ('SENSOR', models.CharField(blank=True, choices=[('CTD_PRES', 'CTD_PRES'), ('CTD_TEMP', 'CTD_TEMP'), ('CTD_CNDC', 'CTD_CNDC'), ('IDO_DOXY', 'IDO_DOXY'), ('OPTODE_DOXY', 'OPTODE_DOXY')], max_length=25, null=True)),
                ('SENSOR_MAKER', models.CharField(blank=True, choices=[('AANDERAA', 'AANDERAA'), ('AMETEK', 'AMETEK'), ('SATLANTIC', 'SATLANTIC'), ('SEB', 'SBE'), ('WETLABS', 'WETLABS')], max_length=25, null=True)),
                ('SENSOR_MODEL', models.CharField(blank=True, choices=[('SBE41CP', 'SBE41CP')], max_length=25, null=True)),
                ('SENSOR_SERIAL_NO', models.CharField(blank=True, max_length=25, null=True)),
                ('PREDEPLOYMENT_CALIB_EQUATION', models.CharField(blank=True, max_length=100, null=True)),
                ('PREDEPLOYMENT_CALIB_COEFFICIENT', models.CharField(blank=True, max_length=100, null=True)),
                ('DEPLOYMENT', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensors', to='deployments.deployment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(check=models.Q(('SENSOR__in', ['CTD_PRES', 'CTD_TEMP', 'CTD_CNDC', 'IDO_DOXY', 'OPTODE_DOXY']), ('SENSOR_MAKER__in', ['AANDERAA', 'AMETEK', 'SATLANTIC', 'SEB', 'WETLABS']), ('SENSOR_MODEL__in', ['SBE41CP'])), name='sensors_sensor_SENSOR_CHECKS'),
        ),
    ]
